server:
  addr: 8080

client:
  addr: localhost:9559

gNMIServer:
  addr: localhost:9339

P4InfoPath: k8s_dp/p4Info.txt
p4BinPath: k8s_dp/k8s_dp.pb.bin
DeviceId: 1
P4ProgConf: k8s_dp/k8s_dp.conf
HostName: "Node1"
# Possible debug levels
#  "Panic"
#  "Fatal"
#  "Error"
#  "Warn"
#  "Info"
#  "Debug" (Default)
#  "Trace"
LogLevel: "Debug"
EnableServices: 0
EnableRouting: 0
DefaultDevice: 0
