
resources:
- ./infraagent-configmap.yaml
- ./infraagent-service-account.yaml
- ./infraagent-cluster-role.yaml
- ./infraagent-daemonset.yaml
- ./inframanager-service-account.yaml
- ./inframanager-cluster-role.yaml
- ./inframanager-daemonset.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: infraagent:latest
  newName: localhost:5000/infraagent
  newTag: latest
- name: inframanager:latest
  newName: localhost:5000/inframanager
  newTag: latest
