name: Build and Test

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:

  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: "Set up Go"
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.1

    - name: "Build"
      run: make

    - name: "Test"
      run: make test

    - name: "Create k8s Kind Cluster"
      uses: helm/kind-action@v1.4.0

    - name: "kustomize test"
      run: |
        # https://github.com/kubernetes-sigs/kustomize/issues/2867
        kustomize version

    - name: "docker build"
      run: make docker-build IMAGE_REGISTRY=ghcr.io/ipdk-io/k8s-infra-offload IMAGE_VERSION=main

    - name: "docker deploy"
      run: |
        make deploy IMAGE_REGISTRY=ghcr.io/ipdk-io/k8s-infra-offload IMAGE_VERSION=main
        # getnodes using kubectl
        kubectl get nodes -o wide

    - name: "Login to GitHub Container Registry"
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "push docker images to registry"
      if: github.event_name == 'push'
      run: make docker-push IMAGE_REGISTRY=ghcr.io/ipdk-io/k8s-infra-offload IMAGE_VERSION=main
